<template>
    <div class="text-black">
        PAYMENT SUCCESS
    </div>

    <!-- MATCH /DATABASES/{DATABASE}/DOCUMENTS {

    // THIS RULE ALLOWS ANYONE WITH YOUR FIRESTORE DATABASE REFERENCE TO VIEW, EDIT,
    // AND DELETE ALL DATA IN YOUR FIRESTORE DATABASE. IT IS USEFUL FOR GETTING
    // STARTED, BUT IT IS CONFIGURED TO EXPIRE AFTER 30 DAYS BECAUSE IT
    // LEAVES YOUR APP OPEN TO ATTACKERS. AT THAT TIME, ALL CLIENT
    // REQUESTS TO YOUR FIRESTORE DATABASE WILL BE DENIED.
    //
    // MAKE SURE TO WRITE SECURITY RULES FOR YOUR APP BEFORE THAT TIME, OR ELSE
    // ALL CLIENT REQUESTS TO YOUR FIRESTORE DATABASE WILL BE DENIED UNTIL YOU UPDATE
    // YOUR RULES
    MATCH /{DOCUMENT=**} {
      ALLOW READ, WRITE: IF REQUEST.TIME < TIMESTAMP.DATE(2023, 9, 23);
    }
  },-->
</template>